### ISSUE TITLE
Prepare repo for open world

### ISSUE THREAD

**Issue by worm2fed** [union-platform/ui-kit#1]
I think we must add License file and reuse checks in this repo too, like we have it in our main repo.
Also, we might want add here:
- PR templates
- Issue templates
- clean up `.gitignore` a bit
- maybe smth else

**Comment by worm2fed** [comment]
@ib0man 
To set up templates and CI step to check licenses just copy `.github` directory from our main repo
To set up licenses, you need to copy main license file and directory with same name from our main repo.

Then, see @rexolion open PR in main repo, when it will be ready you can take `.gitignore` and look how to add license identifiers to source files

**Comment by rexolion** [comment]
Fixed in #2
